### ISSUE TITLE
Webpack 5 compatibility

### ISSUE THREAD

**Issue by kelly-tock** [eddyerburgh/react-dev-tools-iframe-webpack-plugin#14]
getting this on webpack 5:

```
[webpack-dev-middleware] TypeError: Cannot read property 'unshift' of undefined
<e>     at /Users/kelly/tock/admin/consumer/node_modules/react-dev-tools-iframe-webpack-plugin/index.js:15:50
<e>     at Array.forEach (<anonymous>)
<e>     at /Users/kelly/tock/admin/consumer/node_modules/react-dev-tools-iframe-webpack-plugin/index.js:10:37
<e>     at Hook.eval [as callAsync] (eval at create (/Users/kelly/tock/admin/consumer/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
<e>     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/kelly/tock/admin/consumer/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
<e>     at Compiler.emitAssets (/Users/kelly/tock/admin/consumer/node_modules/webpack/lib/Compiler.js:808:19)
<e>     at /Users/kelly/tock/admin/consumer/node_modules/webpack/lib/Watching.js:79:21
<e>     at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by echenley** [comment]
We've been using this plugin with webpack 5 for a while now and just got this bug. As a workaround, you can `rm -rf node_modules/.cache/webpack` and rerun webpack to fix the issue. Seems to be something to do with the filesystem cache.
